name: M3U generator

on:
  schedule:
    - cron: '0 */3 * * *'  # Roda a cada 3 horas

  pull_request:
    branches:
      - main

  workflow_dispatch:  # Permite rodar manualmente no GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Instala a biblioteca yt-dlp
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      # 4. Configura credenciais do Git
      - name: Git Config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # 5. Executa o script
      - name: Run autorun.sh
        run: |
          chmod +x autorun.sh
          ./autorun.sh

      # 6. Salva e envia as alterações de volta ao repositório
      - name: Commit and Push
        run: |
          git add -A
          git diff-index --quiet HEAD || git commit -m "Auto-update M3U links [skip ci]"
          git push
